SFTClient/Controllers/HomeController.cs
using NLog;
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Configuration;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using System.Web.Security;

namespace SFTClient.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index( string hwnd )
        {
            if ( Const.CHECK_AUTHORITY )
            {
                if ( checkValidate() == false )
                    return Redirect( Const.SIGNIN_PAGE );
            }

            HttpContext.Session["Auth"] = false;
            HttpContext.Session["UserName"] = string.Empty;
            HttpContext.Session["CompanyId"] = string.Empty;
            HttpContext.Session["Page"] = string.Empty;
            HttpContext.Session["Equipment"] = string.Empty;

            if ( string.IsNullOrEmpty( hwnd ) == false )
                HttpContext.Session["Hwnd"] = hwnd;

            MyConfig.Load( System.Web.HttpContext.Current.Server.MapPath( @"~\config\" ) + Const.SYSTEM_SETTING_FILE );
            HttpContext.Session["CompanyId"] = MyConfig.CompanyId;

            // load version
            Assembly assembly = Assembly.LoadFrom( System.Web.HttpContext.Current.Server.MapPath( @"~\bin\" ) + "SFTClient.dll" );
            ViewData["Version"] = assembly.GetName().Version.ToString();

            string version = string.Empty;
            string filePath = string.Empty;
            if ( MyConfig.LiveUpdate )  // when setting is enabled, redirect to LiveUpdate
            {
                if ( LiveUpdate.CheckVersion( ref version, ref filePath ) )
                    return RedirectToAction( "Update", "Home" );
            }

            // enabled/disabled homepage buttons by ststem setting
            // Model (0: Normal, 1: Equipment Integration, ...)
            if ( MyConfig.EquipTrackinoutModel )
                ViewData["Model"] = 1;
            else
                ViewData["Model"] = 0;

            return View();
        }

        public ActionResult Settings()
        {
            if ( Const.CHECK_AUTHORITY )
            {
                Authority auth = new Authority();
                if ( auth.CheckSessionExist() == false )
                    return Redirect( Const.SIGNIN_PAGE );
            }

            return View();
        }

        public ActionResult Login()
        {
            if ( Const.CHECK_AUTHORITY )
            {
                Authority auth = new Authority();
                if ( auth.CheckSessionExist() == false )
                    return Redirect( Const.SIGNIN_PAGE );
            }

            string version = string.Empty;
            string filePath = string.Empty;

            if ( MyConfig.LiveUpdate )  // when setting is enabled, redirect to LiveUpdate
            {
                if ( LiveUpdate.CheckVersion( ref version, ref filePath ) )
                    return RedirectToAction( "Update", "Home" );
            }

            string userName = MyConfig.UserName;
            string password = MyConfig.Password;

            ViewData["UserName"] = userName;
            ViewData["Password"] = password;

            return View();
        }

        public ActionResult Update()
        {
            if ( Const.CHECK_AUTHORITY )
            {
                Authority auth = new Authority();
                if ( auth.CheckSessionExist() == false )
                    return Redirect( Const.SIGNIN_PAGE );
            }

            return View();
        }

        #region >>> private Method <<<

        private bool checkValidate()
        {
            bool bIsPass = false;
            string szProjName, szNodeName, szWaPath;

            NameValueCollection nvc = Request.Form;
            string codepage = nvc["codePage"];

            if ( !string.IsNullOrEmpty( nvc["projName"] ) && !string.IsNullOrEmpty( nvc["nodeName"] )
                && !string.IsNullOrEmpty( nvc["waPath"] ) )
            {
                NameValueCollection parsedNvc = HttpUtility.ParseQueryString(
                Request.RawUrl.Substring( Request.RawUrl.IndexOf( '?' ) + 1 ), Encoding.GetEncoding( Convert.ToInt32( codepage ) ) );
                string decProjName = parsedNvc["proj"];
                string decNodeName = parsedNvc["node"];

                szProjName = decProjName;
                szNodeName = decNodeName;
                szWaPath = nvc["waPath"];

                Session.Add( Const.SESSION_PROJ_NAME, szProjName );
                Session.Add( Const.SESSION_NODE_NAME, szNodeName );
                Session.Add( Const.SESSION_WAPATH, szWaPath );
                bIsPass = true;
            }
            else if ( Session[Const.SESSION_PROJ_NAME] != null && Session[Const.SESSION_NODE_NAME] != null
                && Session[Const.SESSION_WAPATH] != null )
            {
                szProjName = Convert.ToString( Session[Const.SESSION_PROJ_NAME] );
                szNodeName = Convert.ToString( Session[Const.SESSION_NODE_NAME] );
                szWaPath = Convert.ToString( Session[Const.SESSION_WAPATH] );

                bIsPass = true;
            }
            else
            {
                bIsPass = false;
            }
            return bIsPass;
        }

        #endregion
    }
}

SFTClient/Controllers/MoInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SFTClient.Controllers
{
    public class MoInfoController : Controller
    {
        // GET: MoInfo
        public ActionResult Index()
        {
            if ( Const.CHECK_AUTHORITY )
            {
                Authority authority = new Authority();
                if ( authority.CheckSessionExist() == false )
                    return Redirect( Const.SIGNIN_PAGE );
            }

            if ( HttpContext.Session["UserName"] != null )
                ViewData["UserName"] = Session["UserName"];

            ViewData["Equipment"] = MyConfig.Equipment;

            Session.Add( "Page", Page.MOINFO );

            var auth = Session["Auth"];
            if ( auth != null && Convert.ToBoolean( auth ) == true )
            {
                return View();
            }

            return RedirectToAction( "Login", "Home" );
        }

        public ActionResult Query( string equipment )
        {
            if ( Const.CHECK_AUTHORITY )
            {
                Authority authority = new Authority();
                if ( authority.CheckSessionExist() == false )
                    return Redirect( Const.SIGNIN_PAGE );
            }

            var auth = Session["Auth"];
            if ( auth != null && Convert.ToBoolean( auth ) == true )
            {
                Session.Add( "Equipment", equipment );
                return View();
            }

            return RedirectToAction( "Login", "Home" );
        }
    }
}

SFTClient/Controllers/ReWorkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SFTClient.Controllers
{
    public class ReworkController : Controller
    {
        // GET: ReWork
        public ActionResult Index()
        {
            if ( Const.CHECK_AUTHORITY )
            {
                Authority authority = new Authority();
                if ( authority.CheckSessionExist() == false )
                    return Redirect( Const.SIGNIN_PAGE );
            }

            if ( HttpContext.Session["UserName"] != null )
                ViewData["UserName"] = Session["UserName"];

            ViewData["Equipment"] = MyConfig.Equipment;

            Session.Add( "Page", Page.REWORK );

            var auth = Session["Auth"];
            if ( auth != null && Convert.ToBoolean( auth ) == true )
            {
                return View();
            }

            return RedirectToAction( "Login", "Home" );
        }
        public ActionResult ReworkIn( string equipment )
        {
            if ( Const.CHECK_AUTHORITY )
            {
                Authority authority = new Authority();
                if ( authority.CheckSessionExist() == false )
                    return Redirect( Const.SIGNIN_PAGE );
            }

            var auth = Session["Auth"];
            if ( auth != null && Convert.ToBoolean( auth ) == true )
            {
                Session.Add( "Equipment", equipment );
                return View();
            }

            return RedirectToAction( "Login", "Home" );
        }
        public ActionResult ReworkOut( string equipment )
        {
            if ( Const.CHECK_AUTHORITY )
            {
                Authority authority = new Authority();
                if ( authority.CheckSessionExist() == false )
                    return Redirect( Const.SIGNIN_PAGE );
            }

            var auth = Session["Auth"];
            if ( auth != null && Convert.ToBoolean( auth ) == true )
            {
                Session.Add( "Equipment", equipment );
                return View();
            }

            return RedirectToAction( "Login", "Home" );
        }
    }
}

SFTClient/Controllers/TrackinoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SFTClient.Controllers
{
    public class TrackinoutController : Controller
    {
        public ActionResult Index()
        {
            if ( Const.CHECK_AUTHORITY )
            {
                Authority authority = new Authority();
                if ( authority.CheckSessionExist() == false )
                    return Redirect( Const.SIGNIN_PAGE );
            }

           if ( HttpContext.Session["UserName"] != null )
                ViewData["UserName"] = Session["UserName"];

            ViewData["Equipment"] = MyConfig.Equipment;

            Session.Add( "Page", Page.TRACKINOUT );

            var auth = Session["Auth"];
            if ( auth != null && Convert.ToBoolean( auth ) == true )
            {
                return View();
            }
            return RedirectToAction( "Login", "Home" );
        }

        public ActionResult TrackinForm( string equipment )
        {
            if ( Const.CHECK_AUTHORITY )
            {
                Authority authority = new Authority();
                if ( authority.CheckSessionExist() == false )
                    return Redirect( Const.SIGNIN_PAGE );
            }

            var auth = Session["Auth"];
            if ( auth != null && Convert.ToBoolean( auth ) == true )
            {
                Session.Add( "Equipment", equipment );
                return View();
            }
              
            return RedirectToAction( "Login", "Home" );
        }

        public ActionResult TrackoutForm( string equipment )
        {
            if ( Const.CHECK_AUTHORITY )
            {
                Authority authority = new Authority();
                if ( authority.CheckSessionExist() == false )
                    return Redirect( Const.SIGNIN_PAGE );
            }

            var auth = Session["Auth"];
            if ( auth != null && Convert.ToBoolean( auth ) == true )
            {
                Session.Add( "Equipment", equipment );
                return View();
            }

            return RedirectToAction( "Login", "Home" );
        }

        public ActionResult TableListEmployee()
        {
            return View();
        }
        public ActionResult TableListException()
        {
            return View();
        }
    }
}

SFTClient/Controllers/WipHoldController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SFTClient.Controllers
{
    public class WipHoldController : Controller
    {
        // GET: WipHold
        public ActionResult Index( string moid )
        {
            if ( Const.CHECK_AUTHORITY )
            {
                Authority authority = new Authority();
                if ( authority.CheckSessionExist() == false )
                    return Redirect( Const.SIGNIN_PAGE );
            }

            if ( HttpContext.Session["UserName"] != null )
                ViewData["UserName"] = Session["UserName"];

            if ( string.IsNullOrEmpty( moid ) )
            {
                TempData["MainPage"] = true;
            }
            else
            {
                ViewData["Moid"] = moid;
                TempData["MainPage"] = false;   // means current page is a subpage within equipment integration
            }

            Session.Add( "Page", Page.WIPHOLD );

            var auth = Session["Auth"];
            if ( auth != null && Convert.ToBoolean( auth ) == true )
            {
                return View();
            }

            return RedirectToAction( "Login", "Home" );
        }
    }
}

SFTClient/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    ViewBag.TopTitle = "";
    
    const string Hide = "hide";
    string trackinout = string.Empty;
    string simpleTrack = string.Empty;
    string none = string.Empty;
    string equipIntegrate = string.Empty;
    
    if((int)ViewData["Model"] == 0)
    {
        none = Hide;
        equipIntegrate = Hide;
    }
    else if((int)ViewData["Model"] == 1)
    {
        trackinout = Hide;
        simpleTrack = Hide;
    }
}

@section Scripts{
    <script src="~/Scripts/app/home/index.js"></script>
}

@section Styles{
    <style>
        body {
            background-color: #424242;
        }

        .header {
            background-color: #FFFFFF;
        }
    </style>
}
<div class="content">
    <div class="dsc-header">
        <span id="network">
            <img src="~/Content/img/online.png" class="online" alt="ONLINE">
            <img src="~/Content/img/offline.png" class="offline hide" alt="OFFLINE">
        </span>
    </div>
    <!--First Row-->
    <div class="home-container row" style="margin-top: 20px;">
        <div class="col-md-4 rt @trackinout" id="trackinout">
            <a href="@Url.Action("Index", "Trackinout")" class="homebtn color-style-6">
                <span class="home-text five-char">進出站報工</span>
                <img src="~/Content/img/home_trackinout.png" class="home-img">
            </a>
        </div>
        <div class="col-md-4 ct @simpleTrack" id="simpleTrack">
            <a href="@Url.Action("Index", "SimpleTrack")" class="homebtn color-style-5">
                <span class="home-text">簡易報工</span>
                <img src="~/Content/img/home_simpletrack.png" class="home-img">
            </a>
        </div>
        <div class="col-md-4 ct @none" id="none">
        </div>
        <div class="col-md-4 ct @equipIntegrate" id="equipIntegrate">
            <a href="@Url.Action( "Index", "EquipIntegrate")" class="homebtn color-style-7">
                <span class="home-text">設備整合</span>
                <img src="~/Content/img/home_eq_integrate.png" class="home-img">
            </a>
        </div>
        <div class="col-md-4 lt" id="moInfo">
            <a href="@Url.Action("Index", "MoInfo")" class="homebtn color-style-1">
                <span class="home-text">製令查詢</span>
                <img src="~/Content/img/home_moinfo.png" class="home-img">
            </a>
        </div>
    </div>
    <!--Second Row-->
    <div class="home-container row">
        <div class="col-md-4 rt" id="rework">
            <a href="@Url.Action("Index", "Rework")" class="homebtn color-style-4">
                <span class="home-text">重工</span>
                <img src="~/Content/img/home_rework.png" class="home-img">
            </a>
        </div>
        <div class="col-md-4 ct" id="wipHold">
            <a href="@Url.Action("Index", "WipHold")" class="homebtn color-style-2">
                <span class="home-text">製令暫停</span>
                <img src="~/Content/img/home_wiphold.png" class="home-img">
            </a>
        </div>
        <div class="col-md-4 lt" id="equipStatus">
            <a href="@Url.Action("Index", "EquipStatus")" class="homebtn color-style-3">
                <span class="home-text">設備狀態</span>
                <img src="~/Content/img/home_eq_status.png" class="home-img">
            </a>
        </div>
    </div>
</div>

<div class="footer">
    版本:<span class="version">@ViewData["Version"]</span>
    <a id="btnShutdown" href="javascript: void(0)" class="fr">
        <img src="~/Content/img/shutdown.png">
    </a>
</div>

SFTClient/Views/Home/Login.cshtml
@{
    ViewBag.Title = "登入";
    ViewBag.TopTitle = "登入";

}
@section Scripts{
    <script src="~/Scripts/app/home/login.js"></script>
    <script type="text/javascript">
        var ui = WA.ui;
        var common = WA.common;
        
        var $username = $("#txtUserName");
        var $password = $("#txtPassword");

        if ($username.val() != "" && $password.val() != "") { Login(); }

        $username.on('change', function () {
            var self = $(this);
            common.checkUserIdFormat(self);
        });

        $("#btnLogin").on('click', Login);

        function Login() {
            var source = {
                'UserName': $username.val(),
                'Password': $password.val()
            }
            $.ajax({
                type: "POST",
                dataType: "json",
                url: "/SFTClient/api/Authority/Login/",
                data: JSON.stringify(source),
                contentType: "application/json; charset=utf-8",
                beforeSend: function () { common.ajaxBlockUI(); },
                complete: function () { $.unblockUI(); },
                success: function (output) {
                    if (output.Result == "success")
                    {
                        location.href = "/SFTClient/@Session["page"]/Index";
                    }
                    else {
                        ui.modalView({
                            modalHeader: "系統訊息",
                            modalBody: output.SysMsg,
                            modalFooter: "msgMode",
                            alert: true,
                            size: { w: 350, h: 200 }
                        });
                    }
                },
                error: function (error) {
                    ui.modalView({
                        modalHeader: "系統訊息",
                        modalBody: error.statusText,
                        modalFooter: "msgMode",
                        alert: true,
                        size: { w: 350, h: 200 }
                    });
                }
            });
        }
    </script>
}


<div class="content">
    <a href="@Url.Action("Index", "Home")" class="fn-btn back fixwidth abs" style="right:15px;top:20px;">
        <span class="fn-text">回主選單</span>
        <img src="~/Content/img/logout.png" height="30px">
    </a>

    <div class="dsc-header">
    使用者登入:
        <span>請刷入登入者條碼</span>
    </div>

    <div class="form-container">
        <div class="input-group style1" style="padding-top: 50px;">
            <span class="input-group-title cell">員工代碼</span>
            <input id="txtUserName" class="form-control w75 cell last" type="text" value="@ViewData["UserName"]" disabled="disabled" />
        </div>
        <div class="input-group style1">
            <span class="input-group-title cell">密碼設定</span>
            <input id="txtPassword" class="form-control w75 cell last qwerty" type="password" value="@ViewData["Password"]" />
        </div>
    </div>
    <div class="bottom-panel row">
        <div class="col-md-2"></div>
        <div class="col-md-2"></div>
        <div class="col-md-2"></div>
        <div class="col-md-2"></div>
        <div class="col-md-2"></div>
        <div class="col-md-2">
            <!--input id ="btnLogin" type="button" class="btn lg submit" style="right:15px;top:20px;" value="登入" /-->
            <a id="btnLogin" href="javascript: void(0)" class="fr fn-btn submit fixwidth" style="right:15px;top:20px;">
                <span class="fn-text">登入</span>
                <img src="~/Content/img/logout.png" height="30px">
            </a>
        </div>
    </div>

</div>

SFTClient/Views/Home/Settings.cshtml
@{
    ViewBag.Title = "參數設定";
    ViewBag.TopTitle = "參數設定";
}
@section Scripts{    
    <script src="~/Scripts/app/home/setting.js"></script>

}


<div class="content clearfix row">
    <div class="ip setting-section">
        <div class="ip-header clearfix">
            <ul class="tab fl">
                <li id="static" class="active"><a href="javascript: void(0)">固定IP</a></li>
                <li id ="dhcp" class="last"><a href="javascript: void(0)">DHCP</a></li>
            </ul>
        </div>

        <div class="input-group ipstyle first">
            <span class="input-group-title cell">本地IP</span>
            <input class="form-control w20 cell qwerty-num" id="localIP1" type="text" value="255" maxlength="3" />
            <input class="form-control w20 cell qwerty-num" id="localIP2" type="text" value="255" maxlength="3" />
            <input class="form-control w20 cell qwerty-num" id="localIP3" type="text" value="255" maxlength="3" />
            <input class="form-control w20 cell qwerty-num last" id="localIP4" type="text" value="255" maxlength="3" />

            <!--<input type="button" class="input-group-btn w20 cell last" value="更新"/>-->

        </div>
        <div class="input-group ipstyle">
            <span class="input-group-title cell">子網路遮罩</span>
            <input class="form-control w20 cell qwerty-num" id="localMask1" type="text" value="255" maxlength="3" />
            <input class="form-control w20 cell qwerty-num" id="localMask2" type="text" value="255" maxlength="3" />
            <input class="form-control w20 cell qwerty-num" id="localMask3" type="text" value="255" maxlength="3" />
            <input class="form-control w20 cell qwerty-num last" id="localMask4" type="text" value="255" maxlength="3" />

            <!--<input type="button" class="input-group-btn w20 cell last" value="更新"/>-->
        </div>
        <div class="input-group ipstyle">
            <span class="input-group-title cell">預設閘道</span>
            <input class="form-control w20 cell qwerty-num" id="localGateway1" type="text" value="255" maxlength="3" />
            <input class="form-control w20 cell qwerty-num" id="localGateway2" type="text" value="255" maxlength="3" />
            <input class="form-control w20 cell qwerty-num" id="localGateway3" type="text" value="255" maxlength="3" />

            <input class="form-control w20 cell last qwerty-num" id="localGateway4" type="text" value="255" maxlength="3" />
            <div class="input-group-blank-btn cell last">&nbsp;&nbsp;</div>
        </div>
        <div class="input-group ipstyle">
            <span class="input-group-title cell">伺服器IP</span>
            <input class="form-control w20 cell qwerty-num" id="serverIP1" type="text" value="255" maxlength="3" />
            <input class="form-control w20 cell qwerty-num" id="serverIP2" type="text" value="255" maxlength="3" />
            <input class="form-control w20 cell qwerty-num" id="serverIP3" type="text" value="255" maxlength="3" />

            <input class="form-control w20 cell last qwerty-num" id="serverIP4" type="text" value="255" maxlength="3" />
            <div class="input-group-blank-btn cell last">&nbsp;&nbsp;</div>
        </div>
        <div class="input-group ipstyle">
            <span class="input-group-title cell">通訊埠</span>
            <input class="form-control w60 cell last qwerty-num" id="serverPort" type="text" value="255" />
        </div>
        <div class="input-group ipstyle">
            <span class="input-group-title cell">連線超時(秒)</span>
            <input class="form-control w60 cell last qwerty-num" id="serverTimeout" type="text" value="255" />
        </div>
    </div>
    <div class="setting-section">
        <div class="input-group userstyle">
            <span class="input-group-title cell">預設登入使用者</span>
            <input class="form-control w55 cell last qwerty" id="username" type="text" value="" />
        </div>
        <div class="input-group userstyle">
            <span class="input-group-title cell">密碼設定</span>
            <input class="form-control w55 cell last qwerty" id="password" type="text" value="" />
        </div>
        <div class="input-group userstyle">
            <span class="input-group-title cell">自動登出時間(分)</span>
            <input class="form-control w55 cell last qwerty-num" id="autoLogoutTime" type="text" value="" />
        </div>

        <!--<div class="input-group-divider"></div>-->

        <div class="input-group style3">
            <span class="input-group-title cell">公司代碼</span>
            <input class="form-control w55 cell last qwerty" id="company" type="text" value="" />
        </div>
        <div class="input-group style3">
            <span class="input-group-title cell">預設機台代碼</span>
            <input class="form-control w55 cell last qwerty" id="equipment" type="text" value="" />
        </div>
        <div class="input-group style3">
            <span class="input-group-title cell">工件技術功能選擇</span>
            <input class="form-control w55 cell last qwerty-num" id="equipDataCollection" type="text" value="" />
        </div>
        <div class="input-group-note">
            <div class="row">
                <div class="col-md-6">
                    <span><b>0</b>&nbsp;&nbsp;標準(沒接,手動)</span><br>
                </div>
                <div class="col-md-6">
                    <span><b>1</b>&nbsp;&nbsp;設備整合</span><br>
                </div>

            </div>
        </div>

        <div class="input-group style3">
            <span class="input-group-title cell">系統整合選擇</span>
            <input class="form-control w55 cell last qwerty-num" id="systemModel" type="text" value="" />
        </div>
        <div class="input-group-note">
            <div class="row">
                <div class="col-md-4">
                    <span><b>0</b>&nbsp;&nbsp;SFP</span><br>
                </div>
                <div class="col-md-4">
                    <span><b>1</b>&nbsp;&nbsp;WIP</span><br>
                </div>
                <div class="col-md-4">
                    <span><b>2</b>&nbsp;&nbsp;其他</span><br>
                </div>
            </div>
        </div>

    </div>
</div>
<div class="bottom-setting">
    <div class="fixarea">
        <!--<div class="btn lg submit">確認</div>-->
        <input id="btnSumit" type="button" class="btn lg submit" value="確認" />

    </div>
    <div class="option-panel">
        <div class="row">
            <div class="col-md-4">
                <ul class="lang-list">
                    <li>
                        <input tabindex="1" type="radio" id="tc-lang" name="lang">
                        <label for="tc-lang">繁體中文</label>
                    </li>
                    <li>
                        <input tabindex="2" type="radio" id="sc-lang" name="lang">
                        <label for="sc-lang">簡體中文</label>
                    </li>
                    <li>
                        <input tabindex="3" type="radio" id="en-lang" name="lang">
                        <label for="en-lang">English</label>
                    </li>
                </ul>
            </div>
            <div class="col-md-4">
                <ul class="lang-list">
                    <li>
                        <input type="checkbox" id="equipTrackinoutModel">
                        <label for="equipTrackinoutModel">開啟設備報工</label>
                    </li>
                    <li>
                        <input type="checkbox" id="gstate2">
                        <label for="gstate2">只開設備狀態</label>
                    </li>
                    <li>
                        <input type="checkbox" id="gstate3">
                        <label for="gstate3">隱藏整批製令暫停</label>
                    </li>

                </ul>
            </div>
            <div class="col-md-4">
                <ul class="lang-list">
                    <li>
                        <input type="checkbox" id="gstate4">
                        <label for="gstate4">多餘數自動帶入</label>
                    </li>
                    <li>
                        <input type="checkbox" id="liveUpdate">
                        <label for="liveUpdate">開啟自動更新</label>
                    </li>
                </ul>
            </div>
        </div>


    </div>
</div>

SFTClient/Views/Home/Update.cshtml
@{
    ViewBag.Title = "系統更新";
    ViewBag.TopTitle = "系統更新";
}
@section Scripts{
<script src="~/Scripts/app/home/update.js"></script>

}